name: Build and Push Docker Image

# Ten workflow uruchomi się, gdy commit zostanie wypchnięty do repozytorium
# ale TYLKO wtedy, gdy zmiany dotyczą pliku Dockerfile.
on:
  push:
    branches:
      - '**' # Uruchom dla każdej gałęzi
    paths:
      - 'Dockerfile' # Tylko jeśli Dockerfile został zmieniony

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Uprawnienie do zapisu w GitHub Packages (Container Registry)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            # Tag z nazwą brancha (np. "feature-x", "develop")
            type=ref,event=branch
            # Tag "latest" tylko dla brancha "main"
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
